export const environment = {
  firebase: {
    projectId: 'mantyres',
    appId: '1:766684296899:web:8d18789f5d94ce68b59476',
    storageBucket: 'mantyres.appspot.com',
    locationId: 'europe-west',
    apiKey: 'AIzaSyC3ssvELWIy0bCnkiSlv5J4zCeu4QkBc9g',
    authDomain: 'mantyres.firebaseapp.com',
    messagingSenderId: '766684296899',
    measurementId: 'G-0VDQT3MTXE',
  },
  production: false,
  PROXY_URL: 'https://cors-anywhere.herokuapp.com/',
  GOOGLE_PLACE_URL: 'https://maps.googleapis.com/maps/api/place/',
  GOOGLE_MAPS_API_KEY: 'AIzaSyDkxjqWpry4Gp2gNprd-dtiOhShY5YnbP0',
  GOOGLE_PLACE_PHOTO: 'https://maps.googleapis.com/maps/api/place/photo?maxwidth=400&photoreference=',
  GA_ID: '766684296899-05uqa430lpvjrvi05s7ssm7hl2bpvduq.apps.googleusercontent.com',
  FB_ID: '756292482221892',
  BASE_URL: 'https://localhost:7250/api/',

  Error:           'https://localhost:7250/api/Error',
  role:            'https://localhost:7250/api/RolesManager/All', 
  utente:          'https://localhost:7250/api/UserManager/',
  login:           'https://localhost:7250/api/AccountManager/Login',
  profile:         'https://localhost:7250/api/AccountManager/Profile',
  password:        'https://localhost:7250/api/AccountManager',
  languages:       'https://localhost:7250/api/Language/',
  currencies:      'https://localhost:7250/api/Currency/',
  country:         'https://localhost:7250/api/Country/',
  city:            'https://localhost:7250/api/City/',
  place:           'https://localhost:7250/api/Place/',
  clienti:         'https://localhost:7250/api/Clienti',
  veicoli:         'https://localhost:7250/api/Veicoli',
  pneumatici:      'https://localhost:7250/api/Pneumatici',
  sedi:            'https://localhost:7250/api/Sedi',
  stagioni:        'https://localhost:7250/api/Stagioni',
  depositi:        'https://localhost:7250/api/Depositi',
  dashboard:       'https://localhost:7250/api/Dashboard',
  inventario:      'https://localhost:7250/api/Inventario',
  excel:           'https://localhost:7250/api/Excel',
  firstConnection: 'https://localhost:7250/api/FirstConnection/',
};
